project:
  type: website
  output-dir: _site

website:
  title: "Dan Li"
  site-url: https://dan-li-o.github.io/
  description: "Personal website built with Quarto"
  repo-url: https://github.com/dan-li-o/dan-li-o.github.io
  repo-actions: [issue, edit]
  navbar: false
  search: false

format:
  html:
    theme: none
    css: [assets/css/main.css]
    include-after-body: assets/js/main.js
    toc: false
    smooth-scroll: false
    anchor-sections: false
    code-copy: false
    code-tools: false

editor: visual
